version: '3.8'

services:
  upload:
    build: .
    volumes:
      - ~/uploads:/app/uploads
    ports:
      - 3000:3000
    restart: always

  nginx:
    image: nginx:latest
    ports:
      - 8443:8443
    volumes:
      - ~/certs:/etc/nginx/certs:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - upload
    restart: always